### ISSUE TITLE
Release Go Program as a CLI?

### ISSUE THREAD

**Issue by modulexcite** [jvns/dns-lookup#2]
Hi @jvns,

Thank you for providing a great tool, love it! Thank you for always providing such great material on your blog as well!
 
If I may, are there any plans to release the DNS program that makes the queries as a CLI tool in the future? Definitely could use this for getting all the record types which is currently not something we can do with `dig` in most cases. If you know of any other programs that can do this, please let me know!

Thank you again!

**Comment by jvns** [comment]
I don't know of another tool that does that. I don't think I want to maintain that CLI tool, but it should be pretty straightforward to take this code and make a CLI tool that does what you suggested (and it's a great idea!)

One thing to note is that there are more DNS record types than this code handles -- I'm not sure what the best place to find a complete list is.

**Comment by BlackthornYugen** [comment]
@jvns would you consider adding something like this to the README.md that just wraps the web service into a function that could be put in .bashrc or .zshrc? 

```bash
webdig () {
	if [[ -z "$*" || "$1" == "--help" || "$1" == "-h" ]]
	then
		echo "Usage: $0 <domain> [<type>]"
		echo "Example 1: $0 google.ca"
		echo "Example 2: $0 bosch.com mx"
		return
	fi
	curl 'https://dns-lookup.jvns.ca/.netlify/functions/dns' -4 --data-raw '{"name":"'$1'.","type":"'${2:-a}'"}' --header "content-type: application/json" --silent --header "x-webdig-command: $0 $*" | jq
}
```

It wouldn't have the "give me all the records" since that was implemented client side I believe, but would be nice for people like me who spend most of their workday behind an http proxy where the basic dig command won't work.
